FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all Python modules
COPY *.py .

RUN mkdir -p downloads

ENV BOT_DOWNLOAD_DIR=/app/downloads

CMD ["python", "main.py"]
